assigness: []
harvest_options:
  goldcopy: true
  path: s3://ooi-data
  refresh: true
  test: false
instrument: CE06ISSP-SP001-08-FLORTJ000
stream:
  method: telemetered
  name: flort_sample
workflow_config:
  schedule: 0 0 * * *
